### ISSUE TITLE
samba setup script broken?

### ISSUE THREAD

**Issue by vvuk** [MiSTer-devel/mr-fusion#18]
I just installed from the latest release about a week ago, and SMB wasn't coming up.

Looking at `/etc/init.d/S91smb`, it has:

```
[ -f /etc/samba/smb.conf ] || exit 0
[ -f /media/fat/linux/samba.sh ] || exit 0
```

but the script in `Scripts/samba_on.sh` only moves `_S91smb` to `S91smb`:
```
mv /etc/init.d/_S91smb /etc/init.d/S91smb > /dev/null 2>&1
```
and doesn't do anything with `/media/fat/linux/_samba.sh`.  Once I manually renamed `/media/fat/linux/_samba.sh` to strip the `_`, everything worked fine.

**Comment by michaelshmitty** [comment]
Hi, thanks for reaching out!

This is not related to Mr. Fusion. The /etc/init.d scripts are maintained by the [Main_MiSTer project](https://github.com/MiSTer-devel/Main_MiSTer/issues).

But it's not an issue there either because you **are** supposed to rename `_samba.sh` to `samba.sh` before you switch it on with the `Scripts/samba_on.sh` script. [See this issue](https://github.com/MiSTer-devel/Main_MiSTer/issues/428) for more info.

Conversely, Mr. Fusion **does** allow you to have a custom `samba.sh` script installed into your MiSTer during the installation with Mr. Fusion. See the [README.md](https://github.com/MiSTer-devel/mr-fusion/blob/master/README.md#custom-samba-configuration-optional) for more info.

Hope that helps. Best regards!
