### ISSUE TITLE
MiSTer_Data partition might not unmount correctly

### ISSUE THREAD

**Issue by michaelshmitty** [MiSTer-devel/mr-fusion#2]
MiSTer_Data partition might not unmount correctly before reboot, possibly causing the volume to get dirty status. Investigate further.

**Comment by michaelshmitty** [comment]
Not an issue. I mistook ```/``` for ```/mnt/data``` in the shutdown log:
```
Stopping network: OK
Saving random seed: OK
Stopping klogd: OK
Stopping syslogd: OK
umount: can't unmount /: Invalid argument
The system is going down NOW!
Sent SIGTERM to all processes
Sent SIGKILL to all processes
Requesting system reboot
```

**Comment by cafink** [comment]
I am currently trying to set up MiSTer on a DE10-nano for the first time, following the steps outlined in this video:  https://www.youtube.com/watch?v=F5__shDTYMQ

The MiSTer Fusion script appears to have funcioned correctly, but when I unplug the device from power, remove the MicroSD card, and then put it into my computer, I am unable to copy any files onto the card.  Any attempt to do so fails with this error:

```Error 0x80071AC3: The operation could not be completed because the volume is dirty. Please run chkdsk and try again.```

chkdsk finds no problems:

```The type of the file system is exFAT.
Volume Serial Number is 0243-EB5C
Windows is verifying files and folders...
Volume label is MiSTer_Data.
File and folder verification is complete.
Windows has checked the file system and found no problems.

   7715840 KB total disk space.
    396832 KB in 18 files.
       192 KB in 6 indexes.
         0 KB in bad sectors.
        64 KB in use by the system.
   7318752 KB available on disk.

     32768 bytes in each allocation unit.
    241120 total allocation units on disk.
    228711 allocation units available on disk.
```

Is this due to this issue?  And what can I do to solve it?  Thanks for your help.
