### ISSUE TITLE
2.9 release file is in a subfolder

### ISSUE THREAD

**Issue by wizzomafizzo** [MiSTer-devel/mr-fusion#22]
The new 2.9 release .zip puts the .img file in a subfolder as opposed to the previous release which is at the root. Still works absolutely fine if you unzip it first, but you can no longer load the release .zip directly into balenaEtcher. Not sure the behaviour in other image writing software.

**Comment by michaelshmitty** [comment]
Thanks for letting me know. I could not reproduce the same situation, but I did mess up the zipping of this release. For starters I zipped the image as `mr-fusion.img`, which is the filename the build process generates. What I usually do is rename that to `mr-fusion-v2.9.im` before zipping it. Then I use zip on mac, now I used 7zip on Debian. Maybe that's what caused it to decompress into a folder for you? Because on my mac it decompressed to root, not a subfolder.

That said, I have fixed the filename and used zip instead of 7zip like I did with all previous releases. I will now upload the new file and I'll ping you if you can check it that would be great. Thanks!

**Comment by grince** [comment]
I can confirm that the re-upload of the release works fine - it can be written on a sd-card with balena etcher and the update works fine with it.
