### ISSUE TITLE
Update MiSTer.ini

### ISSUE THREAD

**Issue by Drakonas** [MiSTer-devel/mr-fusion#26]
The ini is severely outdated at this point, and brings a lot of people asking for help on the MiSTer discord. Updating the ini often fixes the problem.

This is due to massive changes occurring earlier this year that added new options and deprecated the ypbpr setting. RGB, component and composite are selected with newer settings now.

I believe it would be most beneficial to have this updated in the image after all this time and loads of updates.

**Comment by michaelshmitty** [comment]
Has the MiSTer.ini been updated in the latest MiSTer release from https://github.com/MiSTer-devel/SD-Installer-Win64_MiSTer ? Mr. Fusion currently installs Release 20231108 which is a bit outdated. I see the latest one is 20241008. I will build and a release a new image soon that contains the latest release.

This is assuming that the MiSTer.ini file from https://github.com/MiSTer-devel/SD-Installer-Win64_MiSTer has been updated? Can you confirm that? Because Mr. Fusion does not touch the MiSTer.ini that's being shipped.

Thanks for reporting!

**Comment by birdybro** [comment]
The one in the latest zip is identical to the old one. It needs to be updated in the sd-installer repo first and a new zip needs to be made. The ini-settings.sh script will pull down the latest version if you don't have a MiSTer.ini file anyways.

**Comment by michaelshmitty** [comment]
Thanks for checking and confirming @birdybro
Then there is no urgency in releasing a new Mr. Fusion image. I usually only update when when the Linux subsystem updates because that’s a relatively large download during an update right after installing with Mr. Fusion.

For everyone reading this in the future, Mr. Fusion tries not to mangle any upstream releases. It’s just a vehicle for upstream mister and scripts stuff. So usually issues reported here are actually meant to go to the upstream projects. Thanks for your contributions though. Really appreciate it! Happy retro gaming!

**Comment by Drakonas** [comment]
I wasn't aware of that process. Thank you. Should I create an issue requesting this update upstream in the SD installer repo @birdybro? Or is someone already looking to take care of that?

**Comment by Drakonas** [comment]
I should mention that ini-settings.sh isn't included with update_all or Mr fusion as far as I recall, so nobody would know to collect that script.

**Comment by michaelshmitty** [comment]
> I should mention that ini-settings.sh isn't included with update_all or Mr fusion as far as I recall, so nobody would know to collect that script.

Good remark. My thoughts on this:
* Ideally the upstream MiSTer release should keep the ini file up to date. This is assuming that everything in the ini file are settings related to the MiSTer upstream release. If the ini file also contains other settings, I can imagine some pushback on adding those in the release.
* update_all could be asked to include the ini-settings.sh script?
* Mr. Fusion could include the ini-settings.sh script as it does include the regular update and wifi scripts. However, I am reluctant to stretch this to adding more scripts. It's really not up to Mr. Fusion to include arbitrary scripts as a patch for things that should be taken care of upstream imho.
